import { defineConfig } from "vite";
import { vitePluginReactServer } from "vite-plugin-react-server";
import { readdirSync } from "node:fs";
import { resolve } from "node:path";

/**
 * The vprs docs site, statically generated by vprs itself.
 *
 * Dogfooding is the point: this site is React Server Components on stable
 * React, prerendered to static HTML by the plugin it documents, shipping
 * zero client JS for the content. It builds against the repo's HEAD (the
 * package self-reference resolves to ../dist), so a change that breaks SSG
 * breaks this build in the same PR.
 *
 * Build: npm run build:docs-site  (from the repo root; runs under
 * --conditions react-server). Output: docs-site/dist/static.
 *
 * GH Pages serves from a sub-path — the workflow sets BASE_URL (e.g.
 * "/vite-plugin-react-server/") and both Vite and the plugin pick it up.
 */

const DOCS_DIR = resolve(__dirname, "../docs");

// One route per markdown doc: README.md is "/", everything else "/<slug>"
// (subdirectory docs become "/<dir>/<slug>", one level deep).
const pages = [
  "/",
  ...readdirSync(DOCS_DIR, { withFileTypes: true }).flatMap((entry) => {
    if (entry.isDirectory()) {
      return readdirSync(resolve(DOCS_DIR, entry.name))
        .filter((f) => f.endsWith(".md"))
        .map((f) =>
          // a subdirectory's README.md is its index route
          f === "README.md"
            ? `/${entry.name}`
            : `/${entry.name}/${f.replace(/\.md$/, "")}`
        );
    }
    if (entry.name.endsWith(".md") && entry.name !== "README.md") {
      return [`/${entry.name.replace(/\.md$/, "")}`];
    }
    return [];
  }),
];

const base = process.env.BASE_URL || "/";

export default defineConfig({
  root: __dirname,
  base,
  esbuild: { jsx: "automatic" },
  optimizeDeps: { include: ["react-server-dom-esm/client.browser"] },
  plugins: vitePluginReactServer({
    moduleBase: "src",
    Page: "src/page/page.tsx",
    props: "src/page/props.ts",
    moduleBasePath: "",
    moduleBaseURL: base,
    projectRoot: __dirname,
    build: {
      pages,
      assetsDir: "assets",
      client: "client",
      server: "server",
      static: "static",
      outDir: "dist",
    },
    css: { inlineCss: false },
  }),
});
